export const TRADING_CONSTANTS = {
  MAX_LEVERAGE: 2,
  MAX_DAILY_LOSS_PCT: 2,
  MIN_CONFIDENCE_SCORE: 70,
  MAX_RISK_PER_TRADE_PCT: 0.5,
  COOLDOWN_MINUTES_AFTER_LOSS: 30,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY_MS: 1000,
};

export const MARKET_CONSTANTS = {
  DEFAULT_INTERVAL: '1h',
  RSI_PERIOD: 14,
  EMA_FAST: 20,
  EMA_SLOW: 50,
  ATR_PERIOD: 14,
};
